### ISSUE TITLE
docker-compose 文件中的路径问题

### ISSUE THREAD

**Issue by towry** [towry/n#109]
先看下项目结构：

```txt
code/
docker/
     - docker-compose-production.yml
docker-assets
     - webhook/
         - hooks.json
```

我运行命令会在根目录运行，即 `docker-compose -f docker/docker-compose-production.yml up`。

`docker-compose-production.yml`文件中的内容：

```yml
services:
  webhook:
    build:
       context: '../<path-to-dockerfile-dir>'
       dockerfile: 'Dockerfile-webhook'
    volumes:
       - "../docker-assets/webhook/hooks.json:/etc/webhook/hooks.json"
```

上面的配置都是可以正确运行的配置，即正确的配置。从上面可以看到，volumes里面的路径相对的是`docker-compose`配置文件所在的位置，不是你`build`中`context`指定的位置。而`Dockerfile`配置文件中的路径，则是相对于`context`的位置的。
