### ISSUE TITLE
css 去除 元素/svg 的空白符 

### ISSUE THREAD

**Issue by towry** [towry/n#147]
css remove the whitespace of html element.

html 元素的换行符引起的问题是，会在界面上元素的左右有些空白间距。

解决方法是使用 table-cell：

```html
<span>
  <svg></svg>
</span>
```

```css
span {
 display: inline;
}

span > svg {
  display: table-cell;
}
```
