### ISSUE TITLE
css: safari button text not centered.

### ISSUE THREAD

**Issue by towry** [towry/n#48]
```html
<button>this is text</button>
```

```css
button {
width: 100%;
display: flex;
}
```

The button text will not be centered.
The solution is wrap the text in a span, and give the span style: `flex: 1`;

```
button {
  width: 100%;
  display: flex;
}

span {
  flex: 1;
}
```
