### ISSUE TITLE
css query media min-width, max-width

### ISSUE THREAD

**Issue by towry** [towry/n#50]
```css
@media screen and (min-width: 459px) {
	#wave-canvas {
		display: none;
	}
}
```

上面可以理解为，下面的样式有效，直到屏幕的大小小于等于459px。就是屏幕的大小小于459px的话，下面的样式就无效了。

或者可以将 min-width 理解为 from，从这个值一直增大，下面的样式都有效。
max-width: 为 until，从这个值一直减少，下面的样式都有效。
