### ISSUE TITLE
chrome mobile fixed element scroll up and down issue.

### ISSUE THREAD

**Issue by towry** [towry/n#59]
The sidebar is fixed, and the position of menu button is absolute. 

![2f2313d0ba93a6a29f9a55c0fac8f3ec](https://cloud.githubusercontent.com/assets/8279858/19624041/a6232de8-9917-11e6-810b-313039d083de.png)
![72c8535694ef2283ae50d3788a516461](https://cloud.githubusercontent.com/assets/8279858/19624042/a6f1e9da-9917-11e6-8f0a-bde6d0e5dc5c.png)

Issue: When I scroll up or down the page, due to the chrome's `topbar` can slide up and down, the page will scroll up a little or scroll down a little, then the menu button will scroll up or scroll down a little, but it's supposed to be fixed.

The original style for the sidebar wrapper element:

```css
:global(#app-sidebar) {
	position: fixed;
	top: 0;
	bottom: 0;
	height: 100%;
	z-index: $sidebar-index;
	overflow: visible;
	font-size: rem(14px);
	transition: all ease-in-out 200ms;
	transform: none;
}
```

After I change some property value:

```css
:global(#app-sidebar) {
	position: fixed;
	top: inherit;
	bottom: 0;
	height: 100%;
	z-index: $sidebar-index;
	overflow: visible;
	font-size: rem(14px);
	transition: all ease-in-out 200ms;
	transform: none;
}
```

The problem solved.
