### ISSUE TITLE
disabled input color issue

### ISSUE THREAD

**Issue by towry** [towry/n#65]
issue: the color in disabled input is much lighter than the color that I set.

solution:

```scss
&:disabled {
	-webkit-text-fill-color: $clr-black-light;
	-webkit-opacity: 1;
	color: $clr-black-light;
}
```
