### ISSUE TITLE
vertical center issue with transform.

### ISSUE THREAD

**Issue by towry** [towry/n#73]
To do vertical center, we may use the transform way like this:

```css
.vertical-center {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
}
```

This require the parent dom have a height and have two side equal padding. If parent dom only have one side padding, like `padding-top`, then use this way may not work, you have to change `padding-top` to `margin-top`.
